# **Direct Kinematics**

In [1]:
import numpy as np
import pandas as pd

In [2]:
n=int(input("Enter the no of joint's: "))

theta = []
d = []
a = []
alpha = []

for i in range(n):
  theta.append(float(input(f"\nEnter the theta value joint{i+1}: ")))
  d.append(float(input(f"\nEnter the d value joint{i+1}: ")))
  a.append(float(input(f"\nEnter the a value joint{i+1}: ")))
  alpha.append(float(input(f"\nEnter the alpha value joint{i+1}: ")))

data = {
    'Theta': theta,
    'd': d,
    'a': a,
    'Alpha': alpha
}

df = pd.DataFrame(data)
print(f"\n{df}")

Enter the no of joint's: 3

Enter the theta value joint1: 0

Enter the d value joint1: 50

Enter the a value joint1: 0

Enter the alpha value joint1: 90

Enter the theta value joint2: 0

Enter the d value joint2: 0

Enter the a value joint2: 100

Enter the alpha value joint2: 0

Enter the theta value joint3: 0

Enter the d value joint3: 0

Enter the a value joint3: 100

Enter the alpha value joint3: 0

   Theta     d      a  Alpha
0    0.0  50.0    0.0   90.0
1    0.0   0.0  100.0    0.0
2    0.0   0.0  100.0    0.0


In [3]:
T_matrix=[]
for i in range(n):
  theta_i=np.radians(theta[i])
  alpha_i=np.radians(alpha[i])
  d_i=d[i]
  a_i=a[i]

  T=np.array([
   [np.cos(theta_i),-np.sin(theta_i)*np.cos(alpha_i),np.sin(theta_i)*np.sin(alpha_i),a_i*np.cos(theta_i)],
   [np.sin(theta_i),np.cos(theta_i)*np.cos(alpha_i),-np.cos(theta_i)*np.sin(alpha_i),a_i*np.sin(theta_i)],
   [0,np.sin(alpha_i),np.cos(alpha_i),d_i],
   [0,0,0,1]
             ],dtype=np.float32)
  T_matrix.append(T)

fin_transform=np.eye(4)
for i in T_matrix:
  fin_transform=np.dot(fin_transform,i)

for i, T in enumerate(T_matrix):
    print(f"Transformation Matrix for Joint {i + 1}:\n", np.round(T, 3), "\n")

print(f"Final Transformation Matrix:\n{np.round(fin_transform, 3)}")

Transformation Matrix for Joint 1:
 [[ 1. -0.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  1.  0. 50.]
 [ 0.  0.  0.  1.]] 

Transformation Matrix for Joint 2:
 [[  1.  -0.   0. 100.]
 [  0.   1.  -0.   0.]
 [  0.   0.   1.   0.]
 [  0.   0.   0.   1.]] 

Transformation Matrix for Joint 3:
 [[  1.  -0.   0. 100.]
 [  0.   1.  -0.   0.]
 [  0.   0.   1.   0.]
 [  0.   0.   0.   1.]] 

Final Transformation Matrix:
[[  1.   0.   0. 200.]
 [  0.   0.  -1.   0.]
 [  0.   1.   0.  50.]
 [  0.   0.   0.   1.]]
